global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Cerberus-V Control Plane
  - job_name: 'cerberus-ctrl'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker containers monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    
  # System monitoring (node_exporter if available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 5s

  # Cerberus-V GUI Backend
  - job_name: 'cerberus-backend'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Network interface monitoring
  - job_name: 'network-interfaces'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/network/metrics'
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 